version: '3.1'
services :
  db:
    container_name: scs_db
    image: postgres:10-alpine
    ports:
      - 5003:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080
